### PR TITLE
Various Fixes

### LINKED ISSUE #6: The getter 'initialPoint' was called on null.
When using some animations like:  
[https://www.lottiefiles.com/download/117](https://www.lottiefiles.com/download/117)
[https://www.lottiefiles.com/download/28](https://www.lottiefiles.com/download/28)

Flutter throws an exception:

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY╞══
15:39:57.193 269 info flutter.tools I/flutter ( 4620): The following NoSuchMethodError was thrown building MediaQuery(MediaQueryData(size: Size(411.4,
15:39:57.193 270 info flutter.tools I/flutter ( 4620): 683.4), devicePixelRatio: 2.625, textScaleFactor: 1.0, padding: EdgeInsets.zero, viewInsets:
15:39:57.193 271 info flutter.tools I/flutter ( 4620): EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: falsedisableAnimations:
15:39:57.193 272 info flutter.tools I/flutter ( 4620): falseinvertColors: falseboldText: false)):
15:39:57.193 273 info flutter.tools I/flutter ( 4620): The getter 'initialPoint' was called on null.
15:39:57.193 274 info flutter.tools I/flutter ( 4620): Receiver: null
15:39:57.193 275 info flutter.tools I/flutter ( 4620): Tried calling: initialPoint
15:39:57.194 276 info flutter.tools I/flutter ( 4620): 
15:39:57.194 277 info flutter.tools I/flutter ( 4620): When the exception was thrown, this was the stack:
15:39:57.206 278 info flutter.tools I/flutter ( 4620): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:48:5)
15:39:57.206 279 info flutter.tools I/flutter ( 4620): #1      PathParser.parseFromShape (package:lottie_flutter/src/parsers/parsers.dart:286:43)
15:39:57.206 280 info flutter.tools I/flutter ( 4620): #2      AnimatableShapeValue.createAnimation (package:lottie_flutter/src/animatables.dart:167:32)
15:39:57.206 281 info flutter.tools I/flutter ( 4620): #3      new MaskKeyframeAnimation (package:lottie_flutter/src/animations.dart:277:39)
15:39:57.206 282 info flutter.tools I/flutter ( 4620): #4      new BaseLayer (package:lottie_flutter/src/drawing/drawing_layers.dart:59:21)
15:39:57.206 283 info flutter.tools I/flutter ( 4620): #5      new CompositionLayer (package:lottie_flutter/src/drawing/drawing_layers.dart:496:9)
15:39:57.206 284 info flutter.tools I/flutter ( 4620): #6      layerForModel (package:lottie_flutter/src/drawing/drawing_layers.dart:24:18)
15:39:57.206 285 info flutter.tools I/flutter ( 4620): #7      new CompositionLayer (package:lottie_flutter/src/drawing/drawing_layers.dart:504:11)
15:39:57.206 286 info flutter.tools I/flutter ( 4620): #8      _LottieState.setScaleAndCompositionLayer (package:lottie_flutter/src/lottie.dart:91:31)
15:39:57.206 287 info flutter.tools I/flutter ( 4620): #9      _LottieState.didUpdateWidget (package:lottie_flutter/src/lottie.dart:74:5)

Flutter doctor:
[✓] Flutter (Channel beta, v0.8.2, on Linux, locale zh_CN.UTF-8)
    • Flutter version 0.8.2 at /home/ctrysbita/Android/flutter
    • Framework revision 5ab9e70727 , 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2
[✓] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

### PR DESCRIPTION
**Pull request by sroddy**
- Fix mask parsing (should fix #6)
- Fix SplitDimensionPathKeyframeAnimation
- Restore path combine op (even if not perfect, we found out it's actually working as intended in our animations)

### CODE REVIEW

File: lib/src/drawing/elements/paths.dart [hunk 1]
```diff
@@ -133,8 +133,8 @@ class MergePathsDrawable extends AnimationDrawable implements PathContent {
     }
 
     // TODO: figure out why this is broken.
-    // this is broken in android as well - just doesn't show up because it's usually disabled. this fixes some stuff for motorcycle.json
-    return Path.combine(PathOperation.union, firstPath, remainderPath);
+    // this is broken in android as well - just doesn't show up because it's usually disabled.
+    return Path.combine(op, firstPath, remainderPath);
```
Comment (dnfield) [inline lib/src/drawing/elements/paths.dart]: Does the `motorcycle.json` work with this from examples?

Comment (sroddy) [reply lib/src/drawing/elements/paths.dart]: let me take a look

Comment (sroddy) [reply lib/src/drawing/elements/paths.dart]: the problem seems to be limited to Intersect op, so I've added a temporary workaround for the intersect op (forcing it to .union) in order to display it at least as it was before. I can confirm though that Subtract is working as expected.

Comment (dnfield) [reply lib/src/drawing/elements/paths.dart]: The only thing I'm not sure of is where the bug is for that - is it a bug in motorcycle.json, or a bug in parsing, or a bug in Skia, or a bug in Flutter?  Either way, sounds good to me.  I disabled all of them because I didn't have good test cases.
